#!/bin/bash

if [ -f .env ]; then
    export $(cat .env | grep -v '#' | sed 's/\r$//' | awk '/=/ {print $1}')
fi

if [ -n "$GOEXE" ]; then
    goExe="$GOEXE"
else
    goExe="go"
fi

case $1 in

"api")
    cd api &&
        $goExe build -o ../dist/pfila && cd runner && $goExe build -o ../../dist/pfila_runner && cd .. &&
        cd ../dist && sudo ./pfila serve
    ;;
"interface")
    cd interface && yarn dev
    ;;
"build")
    cd api &&
        $goExe build -o ../dist/pfila && cd runner && $goExe build -o ../../dist/pfila_runner && cd ..
    ;;
*)
    echo "Command unknown"
    ;;
esac
