#!/bin/bash
WORKDIR=$(pwd)

case $1 in

"api")
    cd api &&
        go build -o "$WORKDIR/dist/pfila" &&
        cd "$WORKDIR/dist" && sudo ./pfila serve
    ;;
"interface")
    cd interface && yarn dev
    ;;
"build")
    cd api &&
        go build -o "$WORKDIR/dist/pfila" &&
        echo "Compiling interface..." &&
        cd "$WORKDIR/interface" && export ENV="prod" && npx vite build --emptyOutDir

    ;;
*)
    echo "Command unknown"
    ;;
esac
